version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5434:5434
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresql