spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=coalitionbuilder
    username: postgres
    password: postgres
    schema: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database: postgresql