spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=coalitionbuilder
    username: postgres
    password: admin
    schema: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database: postgresql